MVC/ToDo/Models/TodoViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ToDo.Models
{
    public class TodoViewModel 
    {
        [Required(ErrorMessage = "Say What!")]
        public string What   { get; set; }
        [Range(1, 5)]
        public int Priority { get; set; }
        [UIHint("Date")]
        public DateTime When { get; set; }
    }
}

MVC/ToDo/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using InMemoryRepository;
using ToDo.Models;

namespace ToDo.Controllers
{
    public class TodoController : Controller
    {
        readonly IToDoRepository _repository;

        public TodoController(IToDoRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Index()
        {
            var models = _repository.Entities().Select(entity => new TodoViewModel { What = entity.Description, When = entity.CompletionDate, Priority = entity.Priority }).ToList();

            // populate

            return View(models);
        }

        public ActionResult New()
        {
            return View(new TodoViewModel{When = DateTime.Now});
        }

        public ActionResult Create(TodoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("New", model);
            }
            //_repository.Create(new Todo());
            return RedirectToAction("Index");
        }
    }
}

MVC/ToDo/Views/Shared/DisplayTemplates/date.cshtml
@model DateTime

@Html.Label(Model.ToLongDateString())

MVC/ToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="wrapper">
        <div class="mainbody">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC/ToDo/Views/Todo/Index.cshtml
@model IEnumerable<ToDo.Models.TodoViewModel>

@{
    ViewBag.Title = "title";
}

<h2>title</h2>

<div class="todos">
    <ul>
        @foreach (var item in Model)
        {
            @Html.Partial("_TodoItem", item)
        }
    </ul>
    @Html.ActionLink("Get me something else todo!", "New", "Todo")
</div>

MVC/ToDo/Views/Todo/New.cshtml
@model ToDo.Models.TodoViewModel

@{
    ViewBag.Title = "title";
}

<h2>title</h2>

@using(Html.BeginForm("Create", "Todo"))
{
    <p>
        @Html.LabelFor(m => m.What):
    </p>
    <p>
        @Html.TextBoxFor(m => m.What, new{placeholder = "What"}) @Html.ValidationMessageFor(m => m.What)
    </p>
    <p>
        @Html.LabelFor(m => m.Priority):
    </p>
    <p>
        @Html.TextBoxFor(m => m.Priority) @Html.ValidationMessageFor(m => m.Priority)
    </p>
    <p>
        @Html.LabelFor(m => m.When): @Html.DisplayFor(m => m.When)
    </p>
    <p>
        @Html.EditorFor(m => m.When) 
    </p>
    
    <input type="submit" value="Add more work!"/>    
}

MVC/ToDo/Views/Todo/_TodoItem.cshtml
@model ToDo.Models.TodoViewModel

<li>
    <div class="priority">@Model.Priority</div>
    <span class="what">@Model.What</span>
    <span class="when">@Html.DisplayFor(m => m.When)</span>
</li>